name: Dotnet Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          2.1.x
          2.2.x
          3.1.x
          5.0.x
          6.0.x
          7.0.x
          8.0.x
    - name: Build with dotnet
      run: dotnet build -c Release
