name: Dotnet Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.0-preview9-19423-09'
    - name: Build with dotnet
      run: dotnet build -c Release
